<?php
/**
 * Copyright © 2015 pengostores. All rights reserved.
 */
?>
<?php
/**
 * {{controller}} {{action}} template
 *
 * @var $block \Pengo\Ajaxlogin\Block\Login\Index
 */
?>
<div class="ajax-form-create form-holder">
    <button class="action-close" data-role="closeBtn" type="button">
        <span></span>
    </button>
    <h2 class="title"> <span class="base"><?php echo __('Create New Account') ?></span> </h2>
    <div class="message error-message"><span></span></div>
    <div class="message success-message"><span></span></div>
    <form class="form" data-mage-init='{"validation":{}}' action="http://okilucky2.pengostores.mx/customer/account/createpost/" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
        <fieldset class="fieldset create info">
            <legend class="legend"><span><?php echo __('Personal Information') ?></span></legend><br>
            <input type="hidden" name="success_url" value="">
            <input type="hidden" name="error_url" value="">
            

                <div class="field field-name-firstname required">
                <label class="label" for="firstname">
                    <span><?php echo __('First Name') ?></span>
                </label>

                <div class="control">
                    <input type="text" id="firstname"
                           name="firstname"
                           value=""
                           title="First Name"
                           class="input-text required-entry"   data-validate="{required:true}">
                </div>
            </div>
                <div class="field field-name-lastname required">
                <label class="label"  for="lastname">
                    <span><?php echo __('Last Name') ?></span>
                </label>

                <div class="control">
                    <input type="text" id="lastname"
                           name="lastname"
                           value=""
                           title="Last Name"
                           class="input-text required-entry"   data-validate="{required:true}">
                </div>
            </div>
        
                <div class="field required">
                <label for="email_address" class="label"><span> <?php echo __('Correo') ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email_address" value="" title=" Correo" class="input-text" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
                        <div class="field choice newsletter">
                    <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1" id="is_subscribed" class="checkbox">
                    <label for="is_subscribed" class="label"><span><?php echo __('Sign Up for Newsletter') ?></span></label>
                </div>
                                    
                    
                    
                        </fieldset>
            <fieldset class="fieldset create account" data-hasrequired="* Required Fields">
            <legend class="legend"><span><?php echo __('Sign-in Information') ?></span></legend><br>

            <div class="field password required">
                <label for="password" class="label"><span> <?php echo __('Contraseña') ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password" title=" Contraseña" class="input-text" data-validate="{required:true, 'validate-password':true}" autocomplete="off">
                </div>
            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?php echo __('Confirm Password') ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation" title="Confirm Password" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
                </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="<?php echo __('Create an Account') ?>"><span><?php echo __('Create an Account') ?></span></button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    var config_login_class = '<?php echo $block->getClass() ?>';
</script>